[package]
name = "headsetk"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
ksni = "0.2.2"
memoize = "0.4.2"
resvg = "0.43.0"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"

[profile.release]
lto = true
